wallet_test:
  stage: test
  only:
    changes:
      - wallet/**/*
      - taler-kotlin-common/**/*
      - taler-kotlin-android/**/*
      - build.gradle
  script: ./gradlew :wallet:check :wallet:assembleRelease
  artifacts:
    paths:
      - wallet/build/reports/lint-results.html
    expire_in: 1 week
