merchant_test:
  stage: test
  only:
    changes:
      - merchant-terminal/**/*
      - merchant-lib/**/*
      - taler-kotlin-common/**/*
      - taler-kotlin-android/**/*
      - build.gradle
  script: ./gradlew :merchant-terminal:check :merchant-terminal:assembleRelease
  artifacts:
    paths:
      - merchant-terminal/build/reports/lint-results.html
    expire_in: 1 week
